/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementapp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RoomManagement extends javax.swing.JFrame {

    /**
     * Creates new form RoomManagement
     */
    
     Connection conn = null;
       Statement st = null;
       ResultSet rs=null;
       PreparedStatement pst;
       Integer rn;
      
    public RoomManagement() {
        this.pst = null;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setIcon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bedtype = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        roomrate = new javax.swing.JTextField();
        Room = new javax.swing.JTextField();
        BedBox = new javax.swing.JComboBox<>();
        TypeBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        UpdateRoom = new javax.swing.JButton();
        AddRoom = new javax.swing.JButton();
        ShowRoom = new javax.swing.JButton();
        DeleteRoom = new javax.swing.JButton();
        ShowRoom1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(980, 571));
        setMinimumSize(new java.awt.Dimension(980, 571));
        setPreferredSize(new java.awt.Dimension(980, 571));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementapp/dhon.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 125));

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        bedtype.setBackground(new java.awt.Color(255, 255, 255));
        bedtype.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        bedtype.setText("Bed Type     :");

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        type.setText("Room Type :");

        cost.setBackground(new java.awt.Color(255, 255, 255));
        cost.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        cost.setText("Room Rate  :");

        num.setBackground(new java.awt.Color(255, 255, 255));
        num.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        num.setText("Room No    :");

        BedBox.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        BedBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));

        TypeBox.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NonAC" }));
        TypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bedtype, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Room)
                    .addComponent(BedBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeBox, 0, 198, Short.MAX_VALUE)
                    .addComponent(roomrate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedtype, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BedBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomrate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        UpdateRoom.setBackground(new java.awt.Color(255, 255, 255));
        UpdateRoom.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        UpdateRoom.setText("Update Room");
        UpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRoomActionPerformed(evt);
            }
        });

        AddRoom.setBackground(new java.awt.Color(255, 255, 255));
        AddRoom.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        AddRoom.setText("Add Room");
        AddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomActionPerformed(evt);
            }
        });

        ShowRoom.setBackground(new java.awt.Color(255, 255, 255));
        ShowRoom.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        ShowRoom.setText("Show Room");
        ShowRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowRoomMouseClicked(evt);
            }
        });
        ShowRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRoomActionPerformed(evt);
            }
        });

        DeleteRoom.setBackground(new java.awt.Color(255, 255, 255));
        DeleteRoom.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        DeleteRoom.setText("Delete Room");
        DeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoomActionPerformed(evt);
            }
        });

        ShowRoom1.setBackground(new java.awt.Color(255, 255, 255));
        ShowRoom1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        ShowRoom1.setText("Back");
        ShowRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRoom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddRoom)
                .addGap(18, 18, 18)
                .addComponent(UpdateRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeBoxActionPerformed

    private void AddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomActionPerformed
        conn=(Connection) DBconnection.GetConnection();
        if (Room.getText().equals("") || TypeBox.getSelectedItem().equals("") || BedBox.getSelectedItem().equals("") || roomrate.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter All the Fields...!");
        } else {
            
            try {
                
                
                
                st = (Statement) conn.createStatement();
                String query = "INSERT INTO  availableroom VALUES('"+Room.getText()+"','"+TypeBox.getSelectedItem().toString()+"','"+roomrate.getText()+"','"+BedBox.getSelectedItem().toString()+"')";
                int rowsAffected = st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, rowsAffected+" 1 Data added..! ");
                Room.setText("");
                TypeBox.setSelectedIndex(0);
                BedBox.setSelectedIndex(0);
                roomrate.setText("");
                
            } catch (SQLException ex) {
                Logger.getLogger(RoomManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_AddRoomActionPerformed

    private void ShowRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowRoomActionPerformed

    private void ShowRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowRoom1ActionPerformed
        Reservation obj = new Reservation();
        obj.show();
        this.hide();
    }//GEN-LAST:event_ShowRoom1ActionPerformed

    private void UpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRoomActionPerformed
        conn=(Connection) DBconnection.GetConnection();
         try {
             st = (Statement) conn.createStatement();
             String sql = "UPDATE availableroom SET RoomNumber= '"+Room.getText()+"',RoomType='"+TypeBox.getSelectedItem().toString()+"',BedType= '"+BedBox.getSelectedItem().toString()+"',RoomCost='"+roomrate.getText()+"' WHERE RoomNumber= '"+Room.getText()+"'";
                     int updateCount =  st.executeUpdate(sql);
                     JOptionPane.showMessageDialog(this, updateCount+" Successfully Update");
                     Room.setText("");
                     TypeBox.setSelectedIndex(0);
                     BedBox.setSelectedIndex(0);
                     roomrate.setText("");
                     
         } catch (SQLException ex) {
             Logger.getLogger(RoomManagement.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_UpdateRoomActionPerformed

    private void DeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoomActionPerformed
       
        conn= (Connection) DBconnection.GetConnection();
        if(Room.getText().equals("")){
            JOptionPane.showMessageDialog(this, "PUT A Room NUMBER..!!");
        }
        else{
         try {
              String sql = "delete from availableroom where RoomNumber =? ";
             pst =   conn.prepareStatement(sql);
              
            
             
             pst.setString(1, Room.getText());
                        
             pst.execute();
              JOptionPane.showMessageDialog(this," Successfully Delete");
              Room.setText("");
              TypeBox.setSelectedIndex(0);
              BedBox.setSelectedIndex(0);
         } catch (HeadlessException | SQLException ex) {
              JOptionPane.showMessageDialog(this,ex);
         
    }//GEN-LAST:event_DeleteRoomActionPerformed
    }
    }
   
    private void ShowRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowRoomMouseClicked
        // TODO add your handling code here:
        
        Showroom obj=new Showroom();
        obj.show();
        this.hide();
        
    }//GEN-LAST:event_ShowRoomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomManagement().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOG.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom;
    private javax.swing.JComboBox<String> BedBox;
    private javax.swing.JButton DeleteRoom;
    private javax.swing.JTextField Room;
    private javax.swing.JButton ShowRoom;
    private javax.swing.JButton ShowRoom1;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JButton UpdateRoom;
    private javax.swing.JLabel bedtype;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel num;
    private javax.swing.JTextField roomrate;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
